# Ciência dos Dados - 2020 / Primeiro Semestre

## Aula 01 - Exercícios Exploratória para Manipular um DataFrame

## Índice

- [Gapminder](#gap)
- [Exercício 1](#ex1)
- [Exercício 2](#ex2)
- [Resumo dos comandos](#resumo-comandos)

___
**IMPORTANTE**: os exercícios marcados com &#x2605;&#x2605;&#x2605; são mais difíceis e vão exigir que você aprenda novas funções do pandas. Recomendamos que vocês tentem fazer esses exercícios mesmo depois da aula.

<div id="gap"></div>

___

## Gapminder

Gapminder é uma fundação sueca independente, sem afiliações políticas, religiosas ou econômicas.
Possui diversas estatísticas socioeconômicas de quase todos países do mundo que podem ser facilmente obtidas por este [link](https://www.gapminder.org/data/).

Para visualizar relações entre alguns indicadores dos países, veja [aqui](https://www.gapminder.org/tools/)

O arquivo `Gapminder.xlsx` contém um *dataset* extraída do software R (mais detalhes [aqui](https://rdrr.io/cran/dslabs/man/gapminder.html)).

Essa base de dados precisa de algumas manipulações antes de iniciar a análise exploratória, entretanto, a mesma irá depender do problema traçado. Nesse *dataframe*, os indicadores estão mensurados para 185 países os quais se repetem entre os anos de 1960 e 2016.

In [1]:
# Importando as bibliotecas necessárias para esta atividade
import pandas as pd

In [2]:
import os
print('Esperamos trabalhar no diretório')
print(os.getcwd())

Esperamos trabalhar no diretório
C:\Users\matfs\Desktop\Ciência dos Dados\CD20-1\aula01

In [3]:
gap = pd.read_excel('Gapminder.xlsx')

Aqui, `gap` é uma variável do tipo `DataFrame`. Cada uma das colunas significa:

- **country**: nome do país;
- **year**: ano;
- **infant_mortality**: mortalidade infantil a cada 1000 nascidos;
- **life_expectancy**: expectativa de vida;
- **fertility**: número médio de filhos por mulher;
- **population**: população do país;
- **gpd**: PIB de acordo com World Bankdev;
- **continent**: continente;
- **region**: região geográfica.

In [4]:
gap.head()

,country,year,infant_mortality,life_expectancy,fertility,population,gdp,continent,region
1,Albania,1960,115.40,62.87,6.19,1636054.0,NaN,Europe,Southern Europe
2,Algeria,1960,148.20,47.50,7.65,11124892.0,1.382815e+10,Africa,Northern Africa
3,Angola,1960,208.00,35.98,7.32,5270844.0,NaN,Africa,Middle Africa
4,Antigua and Barbuda,1960,NaN,62.97,4.43,54681.0,NaN,Americas,Caribbean
5,Argentina,1960,59.87,65.39,3.11,20619075.0,1.083223e+11,Americas,South America

<div id="ex1"></div>

___

### EXERCÍCIO 1

Faça as seguintes manipulações:
 1. Filtre apenas as linhas do ano 2010 e selecione as variáveis: `country`, `gdp`, `population` e `continent`
 1. Guarde o subconjunto anterior em um novo `DataFrame` chamado `gap2010` e, nele, crie a variável `gdp_cap` que contenha o PIB per capita.
 1. Encontre o país com menor PIB per capita em 2010. **Preencha o valor do PIB per capita desse país no campo de resposta do questionário do Blackboard.**

**Dica**: use `gap.dtypes` para saber o tipo de cada variável. Ainda, consulte [aqui](https://cmdlinetips.com/2019/01/3-ways-to-add-new-columns-to-pandas-dataframe/) para entender como criar novas colunas em um *dataframe*.

In [5]:
# Coloque seu código aqui...
gap2010 = gap.loc[gap['year'] == 2010, ['country', 'gdp', 'population', 'continent']]
gap2010['gdp_cap'] = gap2010.gdp/gap2010.population
gap2010.sort_values(by="gdp_cap")

,country,gdp,population,continent,gdp_cap
9288,"Congo, Dem. Rep.",6.961485e+09,65938712.0,Africa,105.575083
9277,Burundi,1.158914e+09,9461117.0,Africa,122.492313
9320,Guinea-Bissau,2.443955e+08,1634196.0,Africa,149.550888
9303,Eritrea,7.711169e+08,4689664.0,Africa,164.429026
9374,Niger,2.781188e+09,16291990.0,Africa,170.708926
9354,Malawi,2.758393e+09,14769824.0,Africa,186.758673
9305,Ethiopia,1.829149e+10,87561814.0,Africa,208.897983
9282,Central African Republic,1.054122e+09,4444973.0,Africa,237.149251
9353,Madagascar,5.026822e+09,21079532.0,Africa,238.469357
9416,Togo,1.595793e+09,6390851.0,Africa,249.699593
9412,Tajikistan,1.918729e+09,7581696.0,Asia,253.073885
9347,Liberia,1.040653e+09,3957990.0,Africa,262.924666
9398,Sierra Leone,1.574303e+09,5775902.0,Africa,272.563941
9357,Mali,4.199859e+09,15167286.0,Africa,276.902450
9283,Chad,3.369354e+09,11896380.0,Africa,283.225167
9435,Zimbabwe,4.032423e+09,13973897.0,Africa,288.568280
9276,Burkina Faso,4.655655e+09,15632066.0,Africa,297.827236
9369,Nepal,8.066415e+09,26875910.0,Asia,300.135499
9390,Rwanda,3.583713e+09,10293669.0,Africa,348.147302
9268,Benin,3.336801e+09,9509798.0,Africa,350.880359
9287,Comoros,2.472310e+08,698695.0,Africa,353.846859
9314,Ghana,8.779397e+09,24317734.0,Africa,361.028597
9367,Mozambique,8.972306e+09,24321457.0,Africa,368.904948
9322,Haiti,3.697138e+09,9999617.0,Americas,369.727956
9342,Kyrgyz Republic,2.030624e+09,5464567.0,Asia,371.598408
9422,Uganda,1.270110e+10,33149417.0,Africa,383.146862
9434,Zambia,5.587390e+09,13917439.0,Africa,401.466811
9413,Tanzania,1.996568e+10,45648525.0,Africa,437.378414
9415,Timor-Leste,4.805401e+08,1057122.0,Asia,454.573883
9338,Kenya,1.898828e+10,40328313.0,Africa,470.842478
...,...,...,...,...,...
9266,Belgium,2.671431e+11,10929978.0,Europe,24441.320595
9258,Australia,5.630494e+11,22162863.0,Oceania,25405.085940
9280,Canada,8.727845e+11,34126173.0,Americas,25575.222970
9313,Germany,2.069464e+12,80435307.0,Europe,25728.304488
9370,Netherlands,4.411854e+11,16631571.0,Europe,26526.985566
9259,Austria,2.239541e+11,8391986.0,Europe,26686.667187
9331,Ireland,1.234880e+11,4617334.0,Europe,26744.444690
9307,Finland,1.454220e+11,5367693.0,Europe,27092.079270
9425,United Kingdom,1.744580e+12,62716684.0,Europe,27816.842246
9296,Denmark,1.693625e+11,5550959.0,Europe,30510.501115
9387,Qatar,5.690822e+10,1765513.0,Asia,32233.250702
9409,Sweden,3.048587e+11,9382297.0,Europe,32492.973453
9399,Singapore,1.657070e+11,5078961.0,Asia,32626.153769
9326,Iceland,1.077635e+10,318042.0,Europe,33883.405069
9351,"Macao, China",1.852995e+10,534626.0,Asia,34659.653000
9324,"Hong Kong, China",2.511690e+11,6993570.0,Asia,35914.269854
9426,United States,1.154791e+13,309876170.0,Americas,37266.192729
9410,Switzerland,2.947487e+11,7830534.0,Europe,37640.943936
9376,Norway,1.954248e+11,4891251.0,Europe,39953.957113
9335,Japan,5.094423e+12,127319802.0,Asia,40012.806947
9350,Luxembourg,2.651690e+10,507889.0,Europe,52210.039398
9257,Aruba,NaN,101597.0,Americas,NaN
9264,Barbados,NaN,279566.0,Americas,NaN
9297,Djibouti,NaN,830802.0,Africa,NaN
9309,French Polynesia,NaN,268065.0,Oceania,NaN
9316,Greenland,NaN,56546.0,Americas,NaN
9329,Iran,NaN,74253373.0,Asia,NaN
9348,Libya,NaN,6265697.0,Africa,NaN
9371,New Caledonia,NaN,246345.0,Oceania,NaN
9431,West Bank and Gaza,NaN,4068780.0,Asia,NaN

<div id="ex2"></div>

___

### EXERCÍCIO 2 &#x2605;&#x2605;&#x2605;

Faça as seguintes manipulações:
  1. Encontre os cinco maiores países (em tamanho populacional) do ano de 2015;
  1. Filtre apenas as linhas dos cinco países acima considerando todos os anos e com as `country`, `year` , `gdp` e `population`. Guarde esse subconjunto em `gap5`;
  1. Crie a variável `dollar_day` que contenha uma *proxy* da renda per capita diária de cada país;
  1. Responda no Blackboard o valor da renda per capita diária de cada país no ano de 1960, em ordem crescente.

**Dica**: Para filtrar as linhas apenas dos cinco países selecionados no item 1 deste exercício, pesquise por:
  - `isin`: retorna booleano se conteúdo da variável faz parte ou não de uma lista. Consulte sobre esse comando `insin` [aqui](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.isin.html)

In [6]:
# Coloque seu código aqui...
# Coloque seu código aqui...
gap2015 = gap.loc[gap['year'] == 2015, ['country','population']]
gap2015.sort_values(by="population", ascending=False).head(5)
gap5 = gap.loc[gap.country.isin(['China', 'India', 'Indonesia', 'Brazil', 'United States']), ['country', 'year', 'gdp', 'population']]
gap5['dollar_day'] = (gap5.gdp/gap5.population)/365
gap1960 = gap5.loc[gap.year == 1960, :]
gap1960.sort_values(by="dollar_day")

           country  year           gdp   population  dollar_day
35           China  1960  7.034853e+10  644450173.0    0.299070
77           India  1960  8.104265e+10  449661874.0    0.493781
78       Indonesia  1960  1.844892e+10   87792512.0    0.575732
23          Brazil  1960  1.053434e+11   72493585.0    3.981207
176  United States  1960  2.479391e+12  186176524.0   36.486084

<div id="resumo-comandos"></div>

## Resumo dos Comandos

Aqui você encontra um resumo dos comandos apresentados neste notebook:

- [`dtypes`](#ex1): mostra o tipo de cada variável do *dataframe*.
- [`isin`](#ex2): avalia, por exemplo, se conteúdo de uma coluna do *dataframe* faz parte ou não de uma lista.